### ISSUE TITLE
Issue starting up app container

### ISSUE THREAD

**Issue by AlexKalopsia** [chrisvel/wreeto_official#12]
This is what happens if I `docker-compose up`

```
Attaching to wreeto_postgres_1, wreeto_redis_1, wreeto_app_1
postgres_1  | WARNING: no logs are available with the 'db' log driver
redis_1     | WARNING: no logs are available with the 'db' log driver
app_1       | WARNING: no logs are available with the 'db' log driver
wreeto_app_1 exited with code 1
```

My docker-composed looks like this (only edited volumes folders)

```
version: '3.7'
services:
  postgres:
    image: postgres:11
    env_file: .env
    volumes:
    - /volume1/docker/wreeto/postgres-data:/var/lib/postgresql/data
  app:
    image: chrisvel/wreeto:latest
    command: foreman start 
    volumes:
      - /volume1/docker/wreeto/app:/app/wreeto
      - /volume1/docker/wreeto/app/public/assets:/app/wreeto/public/assets
    ports:
      - 8383:8383
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      RAILS_ENV: 'development'
  redis:
    image: redis:5.0.7
```

**Comment by chrisvel** [comment]
You forgot to mention it's on a synology NAS device. Check this out https://github.com/sameersbn/docker-gitlab/issues/1495. They succeed to run gitlab on a synology NAS having the same exact issue by adding 
```
logging:
      driver: json-file
      options:
        max-size: "10m"
```
Can you try this?
