### ISSUE TITLE
Container cannot find docker-entrypoint.sh and cannot start.

### ISSUE THREAD

**Issue by gkoerk** [chrisvel/wreeto_official#24]
Starting the container results in 
`container_linux.go:265: starting container process caused "exec: \"./docker-entrypoint.sh\": stat ./docker-entrypoint.sh: no such file or directory",`

**Comment by chrisvel** [comment]
@gkoerk you need to copy the `docker-entrypoint.sh` file to the root of the same directory where you have placed the `docker-compose.yml` file. 

Also please take a look at the README file and let me know If something's unclear regarding the setup, so I'll improve it.

**Comment by chrisvel** [comment]
@gkoerk did you have the chance to check out my suggestion?

**Comment by chrisvel** [comment]
Closing this issue as it's not active. If there is more information please feel free to re-open.

**Comment by Minkiu** [comment]
Hey, I am trying to get wreeto running, and I am facing the same (it's worth noting that at some point I had it working, but I have since restarted the installation process from a clean slate, i.e removed docker images, containers and volumes), what I've done so far:

I `wget` from the repo the following files into a folder:
`docker-compose.yml`:
```
version: '3.7'
services:
  postgres:
    image: postgres:11
    env_file: .env
    volumes:
    - wreeto_db:/var/lib/postgresql/data
  app:
    image: chrisvel/wreeto:version-2.6.6
    command: foreman start
    volumes:
      - ./wreeto-data:/app/wreeto
      - ./wreeto-data/public/assets:/app/wreeto/public/assets
      - ./wreeto-data/storage:/app/storage
      - ./wreeto-data/backups:/app/backups
    ports:
      - 8383:8383
    depends_on:
      - postgres
      - redis
    env_file: .env
  redis:
    image: redis:5.0.7
volumes:
  wreeto_db:
```
Note: I've created a folder called "wreeto-data" to store all the things realted to wreeto. I guess this could also be converted into a volume, like what I've done with the postgres db.

Then `.env.development.local` and renamed it to `.env`:
```
ENCRYPTION_KEY=0d9f5796221d3fe2d9a42123ad4c5efa
POSTGRES_HOST=localhost
POSTGRES_USER=wreeto_admin
POSTGRES_PASSWORD="my_very_secret_password"
POSTGRES_DB=wreeto_db
POSTGRES_PORT=5432
RACK_ENV=production
RAILS_ENV=production
RAILS_MASTER_KEY=f21ab619787e22f6cb13d3884ca20d78
REDIS_HOST=localhost
REDIS_PASSWORD=
SMTP_USERNAME=
SMTP_PASSWORD=
WREETO_HOST=my.url.domain
WREETO_PORT=8383
```

And the `docker-entrypoint.sh`:
```
#!/bin/sh
set -e

if [ -f /app/wreeto/tmp/pids/server.pid ]; then
  rm /app/wreeto/tmp/pids/server.pid
fi

bundle exec rake db:migrate || bundle exec rake db:setup

exec bundle exec "$@"
```
And did `sudo chmod +x docker-entrypoint.sh`.

So in summary these are the contents of the folder:
```
-rw-r--r--  docker-compose.yml
-rwxr-xr-x  docker-entrypoint.sh
-rw-r--r--  .env
drwxr-xr-x  wreeto-data
```

When running `docker-compose up` this  is what I get:
```
docker-compose up
wreeto_redis_1 is up-to-date
wreeto_postgres_1 is up-to-date
Starting wreeto_app_1 ... error

ERROR: for wreeto_app_1  Cannot start service app: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./docker-entrypoint.sh": stat ./docker-entrypoint.sh: no such file or directory: unknown

ERROR: for app  Cannot start service app: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "./docker-entrypoint.sh": stat ./docker-entrypoint.sh: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.
```

I am on Debian Buster x64.

Any idea what I might be doing wrong?

Also, I was wondering if what the "docker-entrypoint" does should be baked within the wreeto docker image?

Cheers and thanks.
